// This file is auto-generated by Supabase CLI
// Run: npm run db:types to regenerate

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      pandagarde_users: {
        Row: {
          id: string
          email: string
          created_at: string
          updated_at: string
          profile_data?: Json
        }
        Insert: {
          id?: string
          email: string
          created_at?: string
          updated_at?: string
          profile_data?: Json
        }
        Update: {
          id?: string
          email?: string
          created_at?: string
          updated_at?: string
          profile_data?: Json
        }
        Relationships: []
      }
      pandagarde_activities: {
        Row: {
          id: string
          user_id: string
          activity_type: string
          activity_data: Json
          completed_at?: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          activity_type: string
          activity_data: Json
          completed_at?: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          activity_type?: string
          activity_data?: Json
          completed_at?: string
          created_at?: string
        }
        Relationships: []
      }
      pandagarde_progress: {
        Row: {
          id: string
          user_id: string
          activity_id: string
          progress_data: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          activity_id: string
          progress_data: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          activity_id?: string
          progress_data?: Json
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      pandagarde_contact_submissions: {
        Row: {
          id: string
          name: string
          email: string
          message: string
          created_at: string
          status: 'pending' | 'read' | 'replied'
        }
        Insert: {
          id?: string
          name: string
          email: string
          message: string
          created_at?: string
          status?: 'pending' | 'read' | 'replied'
        }
        Update: {
          id?: string
          name?: string
          email?: string
          message?: string
          created_at?: string
          status?: 'pending' | 'read' | 'replied'
        }
        Relationships: []
      }
      pandagarde_newsletter_subscribers: {
        Row: {
          id: string
          email: string
          subscribed_at: string
          is_active: boolean
        }
        Insert: {
          id?: string
          email: string
          subscribed_at?: string
          is_active?: boolean
        }
        Update: {
          id?: string
          email?: string
          subscribed_at?: string
          is_active?: boolean
        }
        Relationships: []
      }
      pandagarde_download_tracking: {
        Row: {
          id: string
          user_id?: string
          download_type: string
          file_name: string
          downloaded_at: string
          ip_address?: string
        }
        Insert: {
          id?: string
          user_id?: string
          download_type: string
          file_name: string
          downloaded_at?: string
          ip_address?: string
        }
        Update: {
          id?: string
          user_id?: string
          download_type?: string
          file_name?: string
          downloaded_at?: string
          ip_address?: string
        }
        Relationships: []
      }
      pandagarde_user_sessions: {
        Row: {
          id: string
          user_id: string
          session_data: Json
          created_at: string
          expires_at: string
        }
        Insert: {
          id?: string
          user_id: string
          session_data: Json
          created_at?: string
          expires_at: string
        }
        Update: {
          id?: string
          user_id?: string
          session_data?: Json
          created_at?: string
          expires_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}