# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!

target 'App' do
  # Capacitor Pods
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
  
  # Capacitor Plugins
  # Add your Capacitor plugins here as needed
  # Example:
  # pod 'CapacitorSplashScreen', :path => '../node_modules/@capacitor/splash-screen'
  
  # Cordova Plugins (if any)
  # Add Cordova plugins here if needed
end

